name: nolikplugin
version: '0.0.1'
main: org.dev.nolikplugin.CommandManager
api-version: '1.21'
authors: [ nolikdevelopment ]
description: My first minecraft plugin
commands:
  calculator:
    description: Считает два числа.
    aliases:
      - calc
      - c
      - cl
    usage: /calculate <num1> <+|-|/|*> <num2>
  message:
    description: Отправляет тестовое сообщение.
    aliases:
      - w
      - message
      - sw
    usage: /m <hello|good>




