name: nolikplugin
version: '0.0.1'
main: org.dev.nolikplugin.CommandManager
api-version: '1.21'
authors: [ nolikdevelopment ]
description: My first minecraft plugin
commands:
  calculator:
    description: Считает два числа.
    aliases:
      - calc
      - c
      - cl
    usage: /calculate <num1> <+|-|/|*> <num2>
  message:
    description: Отправляет тестовое сообщение.
    aliases:
      - w
      - message
      - sw
    usage: /m <hello|good>
  health:
    description: Выдает очки здоровья вашему игроку.
    aliases:
      - heal
      - hl
      - h
    usage: /health <1 - 20>
  inventory:
    description: Открывает склад вашего игрока.
    aliases:
      - inventory
      - inv
    usage: /inventory
  food:
    description: Выдает голод вашему игроку.
    aliases:
      - food
      - fh
      - f
    usage: /food <nickname> <food>
  random:
    description: Показывает информацию о создателе плагина.
    aliases:
      - random
      - r
    usage: /random
